### ISSUE TITLE
Allow colors to be created with RGB hex values

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#1]
See example RGB hex values in [this article](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).
### User Story

As a user, I want to create new `Color` objects using hex values, so that it's more familiar to us web developers.
### Tasks
- [x] Figure out algorithm for converting hex values to red / green / blue `Float` values (added in #15)
  - [ ] Determine if we should support the three-character notation [in the CSS spec](https://developer.mozilla.org/en-US/docs/Web/CSS/color)
- [ ] Extend `Color` class to accept hex values and convert
- [ ] Write RSpec tests
  - One idea for a testing strategy could be changing the string names in [`color.rb`](https://github.com/ruby2d/ruby2d/blob/master/lib/ruby2d/color.rb#L8) back to their original hex values from [clrs.cc](http://clrs.cc), then write RSpec tests to validate the path from string, to hex, to eventual `Float` values.

**Comment by kamishettysreeja25** [comment]
@blacktm 
I would like to work on this issue . Can the algorithm   convert hex to rgb and then call the function to_f(a) [ convert to float] .

**Comment by blacktm** [comment]
@kamishettysreeja25 Awesome! I suppose the algorithm could convert to RGB values first and then convert to floats, or skip and go directly to floats, whatever seems to be most intuitive.
