### ISSUE TITLE
Set window flags, options

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#10]
### User Story

As a user, I want the ability to set various options for the window, like making it borderless, resizable, or fullscreen, so that I can create the perfect experience.
### Tasks
- [x] Design the Ruby 2D API
- [x] Interface with [Simple 2D’s window flags](https://github.com/simple2d/simple2d#the-window)
- [x] Write tests, documentation

**Comment by blacktm** [comment]
This has been implemented 🎉
