### ISSUE TITLE
Add sound

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#3]
### User Story

As a user, I want a Sound class, so that I can load and play short audio samples.
### Tasks
- [x] Design the Ruby 2D API (see file [`sound.rb`](https://github.com/ruby2d/ruby2d/blob/master/lib/ruby2d/sound.rb))
- [x] Interface with [Simple 2D’s audio API](https://github.com/simple2d/simple2d#audio)
- [x] Write manual tests and RSpec tests (if possible)

**Comment by kamishettysreeja25** [comment]
@blacktm 
In the sound.rb file , there is a function for playing the sound . What all extra features are required to implement and what does short audio mean ? does it need to show any error if the length of the audio file exceeds some limit ?
Thank You :)

**Comment by blacktm** [comment]
@kamishettysreeja25 Sounds are pretty simple, so all the user should be able to do is create a sound and play it. Unlike music, sounds can't be paused or stopped, namely because they're intended to be short, like a balloon popping for example. There's no specific length to enforce necessarily, so we'll probably just leave that up to the user's judgement, unless people notice any issues, technical or otherwise.

For some implementation behind-the-scenes, Ruby 2D will interface with the [Simple 2D project](https://github.com/simple2d) for this, which will in turn use [`SDL_mixer` samples](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC16) when creating native windows, and use [`HTMLAudioElement`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement) when using the browser.

Hope that helps!

**Comment by blacktm** [comment]
This has been implemented in e11976895af419e7411ae1d326779ff04909b6ca and natively elsewhere 🎵
