### ISSUE TITLE
Add music

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#4]
### User Story

As a user, I want a Music class, so that I can load and play longer audio samples, like for background music.
### Tasks
- [x] Design the Ruby 2D API
- [x] Interface with [Simple 2D’s audio API](https://github.com/simple2d/simple2d#audio)
- [x] Write manual tests and RSpec tests (if possible)

**Comment by blacktm** [comment]
This has been implemented in e11976895af419e7411ae1d326779ff04909b6ca and natively elsewhere 🎵
