### ISSUE TITLE
Add mouse events

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#5]
### User Story

As a user, I want a DSL for mouse inputs, so that I can capture button clicks and other events.
### DSL Ideas

Here are some examples of how the DSL could look:

``` ruby
on mouse: 'left' do
  puts "mouse left"
end

on mouse: 'right' do
  puts "mouse right"
end

on mouse: 'down' do
  puts "mouse down"
end

on mouse: 'up' do
  puts "mouse up"
end

on mouse: 'any' do
  puts "mouse any"
end
```
### Tasks
- [ ] Design the Ruby 2D API
- [ ] Interface with [Simple 2D’s input API](https://github.com/simple2d/simple2d#input)
- [ ] Write manual tests ([input.rb](https://github.com/ruby2d/ruby2d/blob/master/tests/input.rb) could be expanded) and RSpec tests (if possible)

**Comment by blacktm** [comment]
Other events will probably be useful, but for now `'any'` will just be supported:

```ruby
on mouse: 'any' do |x, y|
  puts "Mouse clicked at: #{x}, #{y}"
end
```
