### ISSUE TITLE
Change text content dynamically

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#6]
### User Story

As a user, I want the ability to change the content of `Text` after it's been initialized, so that I can update the text content dynamically and not have to destroy and create another `Text` object.
### Tasks
- [ ] Design the Ruby 2D API, probably should look something like:
  
  ``` ruby
  t = Text.new(0, 0, 20, "Hello Ruby 2D!")
  
  # change the text content
  t.text = "A different message!"
  ```
- [ ] Interface with [Simple 2D’s text API](https://github.com/simple2d/simple2d#text)
- [ ] Write manual tests and RSpec tests (if possible)

**Comment by mikeappell** [comment]
Worked on this. Implementation seems to be working, but it's worth adding some rspec testing.
