### ISSUE TITLE
Release v0.4.0

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#62]
This issue is for capturing tasks to prepare for the next release of Ruby 2D.

**Simple 2D**
- [x] Implement [#52](https://github.com/simple2d/simple2d/issues/52), resize sprite
- [x] Fix `(SDL_Init) No available video device` on Raspberry Pi (see mailing list) — PR [#54](https://github.com/simple2d/simple2d/pull/54), ready to test
- [x] Update documentation for new API
- [x] Write release notes
- [x] [Prepare v0.6.0 release](https://github.com/simple2d/simple2d#preparing-a-release)

**Simple2D.js**
- [x] Make sure API is updated/consistent with Simple 2D
- [x] Release v0.2.0 to npm

**Ruby 2D**
- [x] Merge #61, `contains?`
- [x] Merge #53, default font — If we can't get working for MRuby, just target MRI for now
  - Skipping, just checking if font file exists for now
- [x] Make PR for named parameters, #48
- [x] Write release notes
- [x] [Prepare release](https://github.com/ruby2d/ruby2d#preparing-a-release) and push v0.4.0 RubyGems
- [x] Update docs on ruby2d.com

**Comment by blacktm** [comment]
Done, hooray! 🕹
