### ISSUE TITLE
Change text color

### ISSUE THREAD

**Issue by blacktm** [ruby2d/ruby2d#7]
### User Story

As a user, I want to change the color of text I create, so that I'm not stuck with just boring white.
### Tasks
- [x] Design the Ruby 2D API, probably should look something like:
  
  ``` ruby
  t = Text.new(0, 0, 20, "Hello Ruby 2D!")
  
  # change text color
  t.color = 'red'
  ```
- [x] Interface with [Simple 2D’s text API](https://github.com/simple2d/simple2d#text)
- [x] Write manual tests and RSpec tests (if possible)

**Comment by blacktm** [comment]
This has been implemented 🎉
